# conda env create -f environment.yml

name: neuromotor
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - black==24.4.2
  - click==8.1.8
  - flake8==7.0.0
  - h5py==3.12.1
  - hydra-core==1.3.2
  - hypothesis==6.124.7
  - jupyterlab=4.3.4
  - levenshtein==0.26.1
  - mypy==1.10.0
  - numba==0.60.0
  - numpy==1.26.4
  - pandas==2.2.2
  - pip==25.0
  - pre-commit==3.7.1
  - pytables=3.10.2
  - pytest==8.3.3
  - python-levenshtein==0.26.1
  - python==3.12.7
  - pytorch::pytorch==2.4.1
  - pyyaml==6.0.2
  - scipy==1.14.1
  - scikit-learn==1.5.2
  - seaborn==0.13.2
  - trio==0.28.0
  - unidecode==1.3.8
  - xgboost==2.1.3
  - pip:
      - matplotlib==3.9.2
      - pytorch-lightning==1.8.6
# variables:
#   # for deterministic algorithms
#   # see: https://docs.pytorch.org/docs/stable/notes/randomness.html#avoiding-nondeterministic-algorithms
#   # see: https://docs.nvidia.com/cuda/cublas/index.html#results-reproducibility
#   CUBLAS_WORKSPACE_CONFIG: ":4096:8"
